### ISSUE TITLE
Question - Can this trigger a Flow directly? Seemingly yes since I believe they are the same behind the scenes?

### ISSUE THREAD

**Issue by patvachon77** [DouglasCAyers/sfdc-process-builder-scheduler#2]

**Comment by douglascayers** [comment]
Hi Pat,

Great question! For this project specifically, the Process Builder that you
configure on the bundled custom object can invoke an autolaunched Flow. But
the tool does not call Flows directly, only indirectly by causing the
Process Builder to run on a schedule and from there you can do what you
want (e.g. invoke a Flow, invoke Apex, update or create records, etc).

Thanks,

Doug
